### ISSUE TITLE
login not working

### ISSUE THREAD

**Issue by rozemek** [SlicewOw/webSPELL_Cups#100]
Hello. I've implement partially your addon into my template but there is one problem. If i go to the login link the page is empty any clue how to fix it ? This is my website : http://6.ip-51-68-143.eu . I attached a 
https://imgur.com/a/pe2mFZe      Screenshot 
https://paste.ofcode.org/aQRuhzsLwcFpyhmRL5iW7u      index.php
https://paste.ofcode.org/38Tp8ku2A6m5YcH7m3tD5cz   /cup/html/navigation.html
https://paste.ofcode.org/GRTgcCBGDuhY96zKFZkv2Y login.php

**Comment by rozemek** [comment]
When i keep refreshing the login website i can see sometimes the fields to login but they dissapear .

**Comment by rozemek** [comment]
This is the template i'm trying to use http://www.demo.e4y.gg/Demo58/index.php

**Comment by SlicewOw** [comment]
Your file "/cup/html/navigation.html" contains PHP calls, right? This is not the correct way.

In PHP files you can add HTML files, but in HTML files you cannot include PHP files (in this way).

**Comment by rozemek** [comment]
The problem is the index.php from my template has the navigation links in it and Your addons navigation is not in index.php but in a html version :/

**Comment by SlicewOw** [comment]
webSPELL is well structured in this point:

- every HTML file is related to an existing PHP file
- navigation.php is existing, navigation.html is existing too

But.. you do not need to take the navigation.php from this add-on. You may edit the existing one from your template.

**Comment by rozemek** [comment]
Oh didn’t know that lol. Thanks for help! Btw is there a way to edit the style of the brackets? To make them look different? Is it just a css file right? And last question how can i add more profile fields to a teams/players profile? I do know i have to add them to the mysql structure that includes editing the profile page php file ?

**Comment by SlicewOw** [comment]
Can you send me your e-mail? Then I can add you.

**Comment by rozemek** [comment]
srozemekt@protonmail.com

**Comment by rozemek** [comment]
Do you do customization for cash? : )
