### ISSUE TITLE
Playoffs beenden und Cup abschließen!

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#102]
Möchte man ein Turnier über das AC - Cups - Details beenden, erfolgt folgender Fehler:

![122](https://user-images.githubusercontent.com/17162324/52441531-25d2d500-2b21-11e9-82d4-4b767f175100.JPG)

**Comment by CallioO** [comment]
bei 2on2 Cup ging das abschließen allerdings:

https://cup-addon.slicewow.de/index.php?site=cup&action=details&id=5

**Comment by SlicewOw** [comment]
Es kann sein, dass es noch einen Fehler beim Erstellen von Brackets gibt. Normalerweise sollte die "max_size" gesetzt werden, sofern weniger Teams als erwartet sich angemeldet haben. Das scheint in dem Falle nicht passiert zu sein.
