### ISSUE TITLE
Add new statistics to cup statistics page

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#105]
https://cup-addon.slicewow.de/admin/admincenter.php?site=page_statistic

Im AC kann man sich ja bereits einige Zahlen ansehen. Diese würde ich jedoch erweitern um

- gespielte Matches
- abgeschlossene Turniere
- registrierte Teams
- Prize pool (sofern ein Geldbetrag als Gewinn eingetragen wurde, wird er addiert.)
- evtl. weitere

**Comment by SlicewOw** [comment]
Zum Thema "Prize pool":
Das ist schwierig umzusetzen, da dort auch Texte zugelassen sind (z.B. 100 EUR). Damit kann ich es nicht mehr addieren. Erweiterungen für die Statistik ist dennoch sinnvoll.

**Comment by CallioO** [comment]
Leuchtet mir ein, dann streich das :)

**Comment by CallioO** [comment]
Was genau ist denn da passiert?
Ich kann keine Zeile finden mit "gespielte Matches" oder "abgeschlossene Turniere" 
Dazu kommt noch, dass bei jeder Aktualisierung eine andere Zahl bei Smilies steht.
Kann zwar eh weg, aber dachte ich sage es trotzdem mal

**Comment by SlicewOw** [comment]
Weiß nicht von welchen Smileys du redest, aber das Cup-Addon hat seine eigenen Statistiken abseits der von webSPELL.

![grafik](https://user-images.githubusercontent.com/18439656/53091721-f8b7f680-3512-11e9-8d90-037be1c38f83.png)
