### ISSUE TITLE
Check-In Zeit -1h

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#111]
https://cup-addon.slicewow.de/index.php?site=cup&action=details&id=9

Irgendwas stimmt mit der Check-In Zeit nicht. 
Änder du mal das Turnier im AC ab auf eine Check-In + Startzeit deiner Wahl (es wird zum Zeitpunkt des Check-Ins keine Aktion möglich sein), stellst du die Check-In Zeit eine Stunde zurück, dann funktioniert es.

**Comment by SlicewOw** [comment]
Duplikat von https://github.com/SlicewOw/webSPELL_Cups/issues/40 ?

**Comment by CallioO** [comment]
Ups, sorry
