### ISSUE TITLE
Turnierbaum

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#113]
https://cup-addon.slicewow.de/index.php?site=cup&action=details&id=10

Das erste Match ist generiert und keiner erhielt eine Nachricht, dass das nächste Match spielbereit ist. 
Tester_12 hat ein Ergebnis eingetragen und auch hier erhielt Tester_02 keine Nachricht.

Dazu kommt, dass bei "bye" (sollte zu Wildcard geändert werden), der Sieger nicht direkt im Turnierbaum weiterrückt. 

![adadasdsant](https://user-images.githubusercontent.com/17162324/53160078-78070200-35c7-11e9-804e-f861937f11d4.JPG)

**Comment by SlicewOw** [comment]
"bye" ist das englische "freilos". Wenn du auf Deutsch umstellst, wird dort "Freilos" angezeigt. Das wird auch so bleiben (orientiert an einer großen Liga).

Es gibt keine direkte Benachrichtigung, allerdings gibt es einen Quicklink (siehe Bild). Eine Benachrichtigung hast du bereits in einem existierenden Ticket gewünscht, daher mache ich das Ticket bei keinen weiteren Fragen zu.

![grafik](https://user-images.githubusercontent.com/18439656/53163972-89eca300-35cf-11e9-9ad6-d5fb6ae7a600.png)

**Comment by CallioO** [comment]
eben diese "Offenen Matches" wurden mir nicht angezeigt

**Comment by SlicewOw** [comment]
Geht auch nicht, da du nicht teil des Turniers bist, lediglich die Test-User sind teil des Cups. Admins bewegen sich ausschließlich im Admin-Panel weitestgehend (an dieser Stelle wäre es die Bracket Ansicht).

**Comment by CallioO** [comment]
Natürlich war ich Teil des Turnieres und ich habe mich ja auch mit fast jedem Test Account eingeloggt und dort wurde auch keine Offene Matches angezeigt. Musste immer über das Turnier zum Bracket und auf das Match klicken.

**Comment by SlicewOw** [comment]
Magst du mir einen Screenshot von einem aktiven Nutzer des Turniers schicken auf dem zu sehen ist, dass kein aktives Match in der Navigation angezeigt wird?

Auf dem Screenshot bist du nicht als aktiver Spieler zu sehen, daher bist du in diesem Fall kein Teil des Cups.

**Comment by CallioO** [comment]
Auf dem ersten Bild was ich gepostet habe  ist zu sehen das Tester 02 keine Naxhricht hat (Ergebnis vom Gegner eingetragen)

**Comment by SlicewOw** [comment]
Ggf. mit https://github.com/SlicewOw/webSPELL_Cups/commit/dba2f23a684ed4bddd8c2ffa6c5babede310866b gefixed?

**Comment by CallioO** [comment]
Scheint wieder zu funktionieren
