### ISSUE TITLE
Show place 1-4 only (cup-details)

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#114]
![aaaaaaaa](https://user-images.githubusercontent.com/17162324/53161731-daadcd00-35ca-11e9-9857-7277c0401ce2.JPG)

Momentan werden noch alle Gewinner untereinander aufgeführt. Das ist sehr unübersichtlich und vor allem unnötig. Mein Vorschlag: Platz 1-3 Nebeneinander, so wie auf der Startseite unter "Übersicht vergangener Cups".

**Comment by SlicewOw** [comment]
Werde es vermutlich so gestalten, dass es ein Mechanismus gibt, dass alle Plätze angezeigt werden durch das Klicken eines Buttons oder so.

**Comment by CallioO** [comment]
Halte ich für unnötig. Platz 1-3 nebeneinander. Fertig. Der Rest interessiert doch niemanden ^^

**Comment by SlicewOw** [comment]
Wenn ich bei einem Turnier mit 64/128 Teams Platz 4 werde, würde ich es schon gerne sehen. Wenn es durch das Klicken eines Buttons ist oder nicht, aber sehen möchte ich das schon.
