### ISSUE TITLE
Wildcard = 16:0

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#115]
Bestätigt man als Admin ein Match mit einer Wildcard (bye?), dann wird man im Turnierbaum eine Runde weitergesetzt. Dies sollte natürlich automatisch passieren - siehe #113 

Die Auslegung, dass die Wildcard mit 16:0 gewertet wird, ist zu sehr auf CS:GO abgestimmt und selbst hier lediglich passend für Best of 1 Modi. ich würde es auf 1:0, 2:0, 3:0 ändern, also je nach Runden Modi anpassen.

**Comment by SlicewOw** [comment]
Ein Automatismus wäre wünschenswert, allerdings hat das keine Prio, da sind andere Themen wichtiger.

Bzgl. des Ergebnisses stimme ich zu.
