### ISSUE TITLE
add to register gameaccount

### ISSUE THREAD

**Issue by iDanielWongi** [SlicewOw/webSPELL_Cups#128]
add to register a game account

**Comment by SlicewOw** [comment]
What do you mean exactly?

**Comment by iDanielWongi** [comment]
When a new member register he can add gameaccount.

**Comment by SlicewOw** [comment]
I do not see any problem here?

![grafik](https://user-images.githubusercontent.com/18439656/54927163-ee25be00-4f11-11e9-8322-f207060a48ed.png)

**Comment by iDanielWongi** [comment]
I intend to add this when you sign up for the site

**Comment by SlicewOw** [comment]
I can imagine to implement a workflow like this:

- login/signup through Steam
- create a CS:GO Gameaccount if game exists for player (dunno if I can get this information from steam)

But as I do not want to change the existing registration template by default, this should be part of your implementation.

**Comment by iDanielWongi** [comment]
There is a way that can make it all easier - just make a connection through Steam
