### ISSUE TITLE
match and (playoff) bracket - Nickname

### ISSUE THREAD

**Issue by iDanielWongi** [SlicewOw/webSPELL_Cups#129]
it's showing the Nickname it should show the game account name.

**Comment by SlicewOw** [comment]
May I ask you why?

**Comment by CallioO** [comment]
The tournament tree (Bracket) should show the Nickname - not the Gameaccount Name?!
Let's have a look - Match #21312 // 76561197968981341 vs 74689798654216? 

Please stay with it and show the nickname in the bracket (at every game)

**Comment by iDanielWongi** [comment]
Think if I'm doing an example tournament of the League of Legends. My name in the game can be a different name from the nickname

**Comment by iDanielWongi** [comment]
> The tournament tree (Bracket) should show the Nickname - not the Gameaccount Name?!
> Let's have a look - Match #21312 // 76561197968981341 vs 74689798654216?
> 
> Please stay with it and show the nickname in the bracket (at every game)

Then it needs to replace the user's Steam ID with the Steam Nickname
