### ISSUE TITLE
Add default country to cup settings file

### ISSUE THREAD

**Issue by SlicewOw** [SlicewOw/webSPELL_Cups#135]
It should be able to define a default country in settings.php - this setting covers the default selection if you create a team for example.

Related file: teams_add.html

**Comment by iDanielWongi** [comment]
I ts not work for me I added all the files. and edit db table name.

**Comment by SlicewOw** [comment]
I need more information. What is not working?

**Comment by iDanielWongi** [comment]
http://prntscr.com/omllv6
http://prntscr.com/omlm0z
It does not save the prizes and show an error.

**Comment by SlicewOw** [comment]
This has nothing do to with this issue?! Create a new one...
