### ISSUE TITLE
Gameaccount bannen

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#14]
Bannt man einen Gameaccount wird er dennoch normal im Profil unter Gameaccounts angezeigt.

**Comment by SlicewOw** [comment]
Gebannte Accounts sind anders zu betrachten - du sperrst Benutzer über die Strafpunkte. Wenn du aber bestimmte Gameaccounts erst gar nicht auf deiner Plattform haben willst, fügst du sie zu dieser Liste hinzu.

Geht nur bei bestimmten Spielen (z.B. Steam-Spiele, die ID ändert sich nicht).
