### ISSUE TITLE
Tournament admin permission

### ISSUE THREAD

**Issue by iDanielWongi** [SlicewOw/webSPELL_Cups#142]
If I want to give someone access to run a tournament.
I don't want him to have permission to delete or edit other tournaments.
Is it possible that only tournaments that the user-created will be allowed for that tournament?

**Comment by SlicewOw** [comment]
For each cup you can access users to manage them without giving them "Cup Admin" rights:

![image](https://user-images.githubusercontent.com/18439656/62409924-a9f0ab80-b5de-11e9-8938-b9db72ae712d.png)


This is not enough?

**Comment by iDanielWongi** [comment]
Yeah but I want to give them create a tournament from zero.

**Comment by SlicewOw** [comment]
Then you should give them Cup Admin rights. I do not see the worth to create such a new permissison like this.
