### ISSUE TITLE
Edit tournament challonge bug

### ISSUE THREAD

**Issue by iDanielWongi** [SlicewOw/webSPELL_Cups#147]
its not save the url

**Comment by SlicewOw** [comment]
What do you mean actually? I cannot reproduce this behavior with my newest commits.

**Comment by iDanielWongi** [comment]
still not working.

**Comment by iDanielWongi** [comment]
Notice: Trying to get property 'participant' of non-object in /public_html/cup/php/includes/cup_details_teams.php on line 15

Warning: Invalid argument supplied for foreach() in /public_html/cup/php/includes/cup_details_teams.php on line 17
﻿

**Comment by SlicewOw** [comment]
I cannot reproduce this in anyway. Please be as detailed as you can. And please use screenshots to make your report more understandable.

**Comment by iDanielWongi** [comment]
When doing a tournament from Challonge
The list of participants receives an error
