### ISSUE TITLE
cup addon frage 

### ISSUE THREAD

**Issue by skdnnskdnn** [SlicewOw/webSPELL_Cups#148]
hallo  lieber  SlicewOw habe da mal an dich eine frage zu deinem script 

wird es auch bald möglich sein das mein eine season laufen lassen kann über ein gewissen zeitraum 
also das es nichts mit cups zutun hab aber  man es dan im admin menü auswählen kann also unter 
cup hinzufügen und season hinzufügen usw 

das wäre  meine frage für heute gewesen 

würde mich natürlich auf eine antwort freuen 

sonst ein tolles script  was du da geschaffen hast

**Comment by SlicewOw** [comment]
moin,

wie stellst du dir das denn genauer vor?

was vorgesehen ist (wann, das ist eine gute frage), ist eine gruppenphase woraus ein playoff turnier entsteht. eine gruppenphase ist in meinem verständnis genau das, was du dir vorstellst?

danke für deine nachricht :) solltest du generelle fragen haben, melde dich bitte auch gerne via email, sodass ich dich zu Slack hinzufügen kann.

**Comment by skdnnskdnn** [comment]
hey ich habe leider kein slack also was meine ich mit gruppenphase also ich stelle mir das so vor das man auch eine liga erstellen kann so meine ich das hast du den auch geplannt das du es auch einbinden möchtest das man zum beispiel wie in der esl eine ladder machen kann das meine ich damit und was ich mir sonst noch wünsche zur team ansicht das man das team auch im admin panel löschen kann das würde noch fehlen weil sonst muss mann das immer via pypmyadmin machen muss wen du das beheben könntest wäre es perfekt und halt was ich noch meine beispiel streams das die nicht richtig angezeigt werden aber danke das du dich hier gemeldet hast :) 

mfg skdnn

**Comment by SlicewOw** [comment]
> hey ich habe leider kein slack
eine einfache registration nach dem erhalt der einladung, mehr ist es an dieser stelle nicht. slack ist ein einfaches chat tool.

> also was meine ich mit gruppenphase also ich stelle mir das so vor das man auch eine liga erstellen kann so meine ich das 
eine eigene liga habe ich aktuell nicht geplant.

> hast du den auch geplannt das du es auch einbinden möchtest das man zum beispiel wie in der esl eine ladder machen kann das meine ich damit
ladder ist ähnlich wie die liga nicht geplant.

> was ich mir sonst noch wünsche zur team ansicht das man das team auch im admin panel löschen kann das würde noch fehlen 
wie in der email geschrieben, wäre es gut, wenn du einzelne issues pro frage/problem/... erstellst, damit ich darauf einzeln eingehen kann

> streams das die nicht richtig angezeigt werden
was meinst du damit?

Absätze wären gut, damit ich nichts übersehe :D
