### ISSUE TITLE
SteamID Finder

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#15]
Der SteamID Finder ist komplett ohne Funktion.

**Comment by SlicewOw** [comment]
Steam API Key eingetragen?

**Comment by CallioO** [comment]
Habe extra für die Seite einen API Key registriert, dort kommt dann "Account nicht gefunden" und über die Community ID, welche ja auch als Beispiel grau hinterlegt ist, tut sich nichts.

**Comment by SlicewOw** [comment]
Auf der Demo-Seite funktioniert der SteamID Finder ohne Probleme.

Bitte um mehr Informationen!

**Comment by SlicewOw** [comment]
Geht auf der Demo Seite: STEAM_1:1:4357806

Aber..: es wäre gut bei dem Problem, wenn du ein Screenshot erstellst :)

(Und deinen Kommentar editierst, damit dein Key nicht öffentlich ist!)

**Comment by CallioO** [comment]
![2](https://user-images.githubusercontent.com/17162324/48564413-a1443200-e8f6-11e8-973c-55a5a40185d0.JPG)

**Comment by SlicewOw** [comment]
Der Key hat in der Suche nichts zu tun. Das muss in der settings.php Datei geschehen!

![image](https://user-images.githubusercontent.com/18439656/48565888-de5df380-e8f9-11e8-8002-80f6a2889f1e.png)

**Comment by CallioO** [comment]
Echt merkwürdig.. Also wenn ich meinen Community Link eingebe und auf Account suchen tippe, dann passiert nichts.

**Comment by SlicewOw** [comment]
Konfigurations-Datei fehlt.
