### ISSUE TITLE
Cup Admin Rechte 

### ISSUE THREAD

**Issue by skdnnskdnn** [SlicewOw/webSPELL_Cups#150]
So als Beispiel ich möchte das Person x nur für Cup Admin zuständig ist und keine Rechte sonst verändern kann ist oder wäre das möglich 

Ich hoffe du weit was ich damit sagen möchte

**Comment by SlicewOw** [comment]
Es gibt das Recht „Cup Admin“, damit ist derjenige auch nur für diese Funktionalität befugt.

**Comment by skdnnskdnn** [comment]
Okay
