### ISSUE TITLE
Nach Auswahl eines Sponsors im Cup - Fatal Error

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#17]
Wählt meinen einen Sponsor bei der Erstellung eines Turnieres aus, dann erscheint folgender Fehler: 

> Fatal error: Uncaught Error: Call to undefined function getsponsor() in /var/www/vhosts/nestic.de/Websites/NOR/admin/cup_admin/includes/cup_details_home.php:241 Stack trace: #0 /var/www/vhosts/nestic.de/Websites/NOR/admin/cup_admin/cup_admin_details.php(342): include() #1 /var/www/vhosts/nestic.de/Websites/NOR/admin/cup.php(41): include('/var/www/vhosts...') #2 /var/www/vhosts/nestic.de/Websites/NOR/admin/admincenter.php(467): include('/var/www/vhosts...') #3 {main} thrown in /var/www/vhosts/nestic.de/Websites/NOR/admin/cup_admin/includes/cup_details_home.php on line 241

Das Turnier lässt sich danach auch nicht mehr aufrufen / editieren.

**Comment by SlicewOw** [comment]
https://github.com/SlicewOw/webSPELL_Cups/issues/12
