### ISSUE TITLE
List of admins is too long

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#18]
Hier kann man jeden User auswählen. Ich denke man sollte die Auswahl auf die begrenzen, welche man auch als Admin im Admincenter zuvor eingetragen hat.

![3](https://user-images.githubusercontent.com/17162324/48604198-57506000-e979-11e8-94b8-62603507641b.JPG)

**Comment by SlicewOw** [comment]
Per Design so gewollt, daher die Gruppierung CupAdmin/User.

**Comment by CallioO** [comment]
Wie verhält sich das wenn 4000 Leute registriert sind? Sprengt es dann den content oder muss man scrollen?
