### ISSUE TITLE
Support Ticket Kategorie

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#42]
Ich kann kein Support Ticket schreiben, weil vermutlich keine Kategorie vorhanden ist.
Ist die Funktion vorhanden? Falls ja muss ich blind sein.

**Comment by CallioO** [comment]
Habe es dann doch noch gefunden. Allerdings erhält man als Admin keine Info (Nachricht, oder über das Admincenter), dass ein neues Ticket verfügbar ist. Man muss über das AC auf Support klicken und dies dann annehmen.

**Comment by SlicewOw** [comment]
Bei myRisk eV gibt es eine überarbeitete "Overview", wenn du dich einloggst. Das bietet webSPELL NOR nicht per Default.
