### ISSUE TITLE
Frequently Asked Question (FAQ)

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#43]
Hier müssen bei der Erstellung zwei Spalten erscheinen.

Links = Deutsch
Rechts = Englisch

damit der Language Switch greifen kann.

**Comment by SlicewOw** [comment]
Das Cup Addon hat kein eigenes FAQ - es existiert nur das, welches webSPELL NOR bereitstellt.

**Comment by SlicewOw** [comment]
Die Problematik die sich stellt: webSPELL NOR bietet den Support von vielen Sprachen an, nicht nur DE und EN. Daher müssten alle möglichen (installierten) Sprachen dort gelistet sein.

Allerdings für dich speziell: du kannst bei deren GitHub Projekt den Vorschlag machen, dass das Nachgezogen werden sollte. Vielleicht bearbeitet das ja jemand in naher Zukunft :)
