### ISSUE TITLE
Create cup teams as cup admin

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#44]
Aktuell hat man keine Möglichkeit ein Team über das AC zu erstellen.
Die Funktion wäre allerdings von Vorteil, dass man Leuten ein Team erstellen kann, die ggf. Probleme bei der Erstellung haben.

**Comment by SlicewOw** [comment]
Funktion wäre ggf. sinnvoll - allerdings, wenn jemand nicht in der Lage ist ein Team zu erstellen, dann ist es ein Problem des Users :smile: an welchen Punkten sollte es einem Benutzer nicht möglich sein ein Team zu erstellen?

**Comment by CallioO** [comment]
Wir haben oft ein Team erstellt und es auch zum Turnier hinzugefügt. Teilweise auch nur aus Nettigkeit, weil man erst kurz vor Turnierbeginn zu Hause gewesen ist und wir die User kannten.. Muss ja nicht umgesetzt werden, war nur nen Vorschlag =)

**Comment by SlicewOw** [comment]
Wie geschrieben, ist eine gute Erweiterung - sollte nur nicht darin ausarten, dass die Admins alle Teams erstellen, weil alle zu faul sind 😄  aber das ist jedem selber überlassen.

**Comment by CallioO** [comment]
Es soll lediglich zur Verfügung stehen um im Fall der Fälle diesen "Service" anbieten zu können :)
