### ISSUE TITLE
Logotype is a must-have, why?

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#45]
_"Das Logotype des Teams wurde nicht übermittelt - falsche Eingabe. (1)"_

Ich würde das Logo nicht als Pflichteingabe ausgeben, da sich oft auch spontan ein paar zusammen tun, die keinem Clan angehören. Denen ist das Logo egal und erspart die lästige Suche / Anpassung an irgendein Bild. Die, die einem Clan angehören, die Laden das Bild auch ohne Pflichtangabe hoch.

Nur ein Vorschlag.

**Comment by SlicewOw** [comment]
Ggf. sollte das eine Möglichkeit sein, die jeder für sich konfigurieren kann in der settings.php - was hälst du davon?

**Comment by CallioO** [comment]
Ist okay
