### ISSUE TITLE
Missing team-details in admincenter

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#46]
Klickt man im AC unter Cup Administration -> Teams auf einen Teamnamen, dann wird man auf folgende Seite weitergeleitet (NOT FOUND): 

http://nor.nestic.de/admin/nor.nestic.de/index.php?site=teams&action=details&id=1

**Comment by SlicewOw** [comment]
Es fehlt das "http" in der HP URL (siehe Installations-Anleitung).
