### ISSUE TITLE
Registrierung - Passwortkriterien + Recaptcha

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#47]
1. Recaptcha
Der aktuelle Sicherheitscode (Zahl +/- Zahl =) ist veraltet und meiner Meinung nach auch teilweise sehr schwer zu erkennen. Hier würde ich das Google Recaptcha verwenden:

https://developers.google.com/recaptcha/

2. Passwort
Es gibt Fehler:
Das Kennwort muss folgende Kriterien erfüllen:
Länge:min. 6 Zeichen, eine Zahl, ein Klein- & Großbuchstaben, ein Sonderzeichen

Hier würde ich Kriterien rausnehmen. Wenn der User ein Passwort vergeben möchte das 1234 ist, dann soll er es machen. Sonderzeichen nerven mich als User auf anderen Seiten auch enorm.

**Comment by CallioO** [comment]
Möchte man sein Passwort ändern, dann spielen die Kriterien aus der Registrierung keine Rolle. Ein Passwort wie "test" oder "134" ist möglich. Nachdem man es geändert hat wird man allerdings auf folgende Seite weitergeleitet: 

nor.nestic.de/logout.php
Diese Seite funktioniert nicht 
nor.nestic.de kann diese Anfrage momentan nicht verarbeiten.
HTTP ERROR 500

**Comment by SlicewOw** [comment]
Das sind leider alles Fehler von webSPELL NOR - ich würde dich bitten diese Themen bei deren GitHub Projekt zu reporten.

Thema URL in der eMail:
Setze "https://" im Admincenter (siehe Installations-Beschreibung des Add-Ons!)

Bis auf das Thema mit dem Logout, da muss ich etwas richtig stellen beim Add-On.
