### ISSUE TITLE
Doppelte Passworteingabe bei Anmeldung

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#48]
Erstellt man, aus welchem Grund auch immer, einen Useraccount über das Admincenter, dann wird das Passwort bei der ersten Eingabe nicht erkannt:

> Du hast ein falsches Passwort eingegeben.

Bei der zweiten Eingabe wird es dann akzeptiert und man ist eingeloggt.

Erstellt man einen Account auf normalem Weg, dann wird das Passwort direkt bei der ersten Eingabe erkannt.

**Comment by SlicewOw** [comment]
webSPELL NOR Thema, habe an dem Modul nichts verändert.
