### ISSUE TITLE
QuickJoin Link Blockade

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#49]
Ich erstelle ein Team und möchte über den Direktlink mit einem anderen Account joinen und es erfolgt folgende Fehlermeldung: 

Das Team nimmt an einem Cup teil, wofür kein Gameaccount eingetragen ist.
Bitte zuerst den Gameaccount eintragen und auf die Aktivierung warten.

Als Cups sind ein RocketLeague (keine Gameaccountaktivierung) und Hearthstone (Gameaccountaktivierung durch Admin) online, wobei lediglich der RocketLeague Cup zur Anmeldung offen ist. Der HS Cup ist als gestartet markiert.

Lösche ich den HS Cup, womit dann kein Cup mehr online ist, welcher eine Aktivierung des Gameaccounts durch den Admin Bedarf, dann funktioniert der QuickJoin Link.

**Comment by SlicewOw** [comment]
Entweder ich habe es nicht verstanden oder es funktioniert wie es zu erwarten ist.

Erklärung:
Wenn ein Cup existiert und ein Team bereits angemeldet ist, dann kann kein User dem Team joinen, wenn er den zugehörigen Gameaccout nicht besitzt (sonst würde es das System umgehen).

**Comment by SlicewOw** [comment]
Noch einmal als Hinweis: es ist komplett unabhängig von der Aktivierung des Gameaccounts oder nicht. Sofern kein aktiver Gameaccount existiert, soll dieser Schutzmechanismus greifen. Ein nicht aktiver Gameaccount entspricht in dem Sinne einem nicht existenten Gameaccount.

Ich prüfe das Scenario bei Zeiten.

**Comment by SlicewOw** [comment]
Blockiert durch: https://github.com/SlicewOw/webSPELL_Cups/issues/56
