### ISSUE TITLE
More teams than possible are checked-in

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#50]
Bei meinem 8'er Testcup ist es möglich, obwohl 8/8 bestätigten Teams eingetragen sind, dass sich weitere Teams einchecken können.

Bestätigte Teams: 9 / 8

**Comment by SlicewOw** [comment]
Kannst du bitte noch einmal verifizieren, dass das Problem mit dem neuesten Commit gelöst ist?

**Comment by CallioO** [comment]
Hast du eine separate Seite wo ich einen Admin Account bekommen könnte? 
Dann brauche ich nicht immer alles neu installieren, oder die Dateien updaten.

**Comment by SlicewOw** [comment]
Du könntest auch Git dafür verwenden, dann geht es verhältnismäßig einfach - bis auf Datenbank Änderungen, aber die kommen nicht allzu oft.

**Comment by SlicewOw** [comment]
Sofern der Bug noch besteht, öffne das Ticket wieder.
