### ISSUE TITLE
Match screenshots cannot be uploaded, comments are not working

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#54]
Bild Upload = ohne Funktion
Kommentare = ohne Funktion

**Comment by SlicewOw** [comment]
- [x] Bild Upload = ohne Funktion

**Comment by SlicewOw** [comment]
Wichtige Notiz: ich musste die Install-Datei für das Cup-Addon anpassen. Siehe den Commit dazu für weitere Details.
