### ISSUE TITLE
Winner team does not go further automatically

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#56]
Team A trägt das Ergebnis ein und Team B bestätigt dieses.. So sollte es im Regelfall sein.
Das Match wird als "bestätigt und abgeschlossen" angegeben, aber man rückt im Turnierbaum kein Match weiter. 

Anders ist es, wenn ein Admin das Ergebnis a) ändert, b) bestätigt oder c) selbst einträgt.

**Comment by CallioO** [comment]
https://cup-addon.slicewow.de/index.php?site=cup&action=details&id=6&page=bracket#content

Unterbreche den Test ab hier. Alle Ergebnisse eingetragen und vom Gegner bestätigt. 
Nach Klick auf den Btn "Runde aktualisieren" im AC passiert nichts.
Ich müsste nun also jedes einzelne Match als Admin bestätigen, damit das Turnier in die nächste Runde geht.

**Comment by SlicewOw** [comment]
Nur als Zusatzinformation: "Runde aktualisieren" bedeutet nur, dass die Informationen innerhalb des Cups aktualisiert werden. Sprich: wenn neue Kommentare unter dem Match zu finden sind, dann wird die Zahl in der Admin-Ansicht aktualisiert. Oder wenn der Status des Matches (Team 1 hat bestätigt, Team 2 nicht) sich ändert, dann wird der Hintergrund angepasst.

Mehr Funktionalität ist hierbei nicht zu erwarten!

**Comment by SlicewOw** [comment]
![grafik](https://user-images.githubusercontent.com/18439656/52344899-3ea59280-2a1c-11e9-9563-4ca1ea04ac7e.png)
