### ISSUE TITLE
Mode "Best-of-X" is wrong in cup matches

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#57]
http://nor.nestic.de/index.php?site=cup&action=match&id=2&mID=7

Hier wird der BO Modus falsch angegeben. Auf der Detailseite steht folgendes:
Cup Format
Viertelfinale: Best of 3
Halbfinale: Best of 3
Finale: Best of 5

und im Pfad oben wird "Rocket League Test / Finale / Match Start: 11.01.2019 - 11:30 / Format: BO1"
angegeben. Ich würde hier ggf neben dem Bild unter Status ein weiteres Feld hinzufügen, welche das nochmal deutlich zeigt.

**Comment by SlicewOw** [comment]
Wieso die Verdeutlichung des Formates (der falsch ist, offensichtlich)?

**Comment by CallioO** [comment]
? Gespeichert ist der Cup mit Bo3 in den Vorrunden und Bo5 im Finale.
Es verwirrt doch nur wenn im Match dann irgendwo Bo1 auftaucht. Verursacht nur Anfragen und unnötigen Stress.

**Comment by SlicewOw** [comment]
Der Modus des kompletten Matches ist falsch.

**Comment by CallioO** [comment]
Der Modus aller Matches ist falsch! Überall steht Bo1.
