### ISSUE TITLE
Teamauszeichnung 

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#59]
Es werden keine Teamauszeichnungen angegeben.

Über das AC habe ich folgende Awards vergeben:
![213nt](https://user-images.githubusercontent.com/17162324/51027940-6ecf5200-1592-11e9-8b6a-3b06c7fd5d87.JPG)

Im Teamprofil wird nichts davon wiedergegeben.
![231nnt](https://user-images.githubusercontent.com/17162324/51027988-89093000-1592-11e9-8b72-834361ba0a0b.JPG)

**Comment by SlicewOw** [comment]
Wird über den Cronjob gespeichert, der 1x täglich laufen sollte (siehe README unter Optional).

**Comment by CallioO** [comment]
Sollte auch automatisch nach Turnierende aktualisiert werden meiner Meinung nach

**Comment by CallioO** [comment]
Ich wollte gerade testen ob der die Awards nun übernommen hat und musste feststellen, dass im AC alle von mir hinzugefügten Awards gelöscht sind (nicht von mir)
