### ISSUE TITLE
Designfehler in index.php?site=teams&action=admin&id=x

### ISSUE THREAD

**Issue by xxxrenegade** [SlicewOw/webSPELL_Cups#64]
Die Buttens oben Rechts werden nicht gescheid im Bootstrap panel-heading ausgegeben.
![unbenannt-1](https://user-images.githubusercontent.com/2109906/51549588-fc505300-1e6a-11e9-9e04-ca40fbee809f.jpg)

**Comment by SlicewOw** [comment]
Bei mir scheint alles i.O. zu sein. Hast du irgendwelche Auffälligkeiten in der Console oder sowas?

![grafik](https://user-images.githubusercontent.com/18439656/51550883-a204c180-1e6d-11e9-9493-f8bb19f5f8d7.png)

**Comment by xxxrenegade** [comment]
```
<div class="clearfix">
  <div class="pull-right">
    <a class="btn btn-default btn-sm" href="index.php?site=teams&amp;action=details&amp;id=1">Team ansehen</a> <a class="btn btn-default btn-sm" href="index.php?site=teams&amp;action=log&amp;id=1">Team Log</a> <a class="btn btn-info btn-sm white darkshadow" href="index.php?site=teams&amp;action=edit&amp;id=1">Team editieren</a> <a class="btn btn-danger btn-sm white darkshadow" href="index.php?site=teams&amp;action=delete&amp;id=1">Team löschen</a>
  </div>
</div>
<br>
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <div class="pull-left">
            <h1 class="panel-title">Test Team</h1>
        </div>
        <div class="pull-right grey">Team erstellt am: 22.01.2019</div>
    </div>
```
Im Allgemeinen sollte das Projekt mal die clear Klasse durch die von Bootstrap vorhandene clearfix Klasse ersetzen. Der Fehler liegt wohl darin das ich die clear klasse nämlich in meinem Projekt nicht verwende weil es in Bootstrap ja schon eine gibt ^^

**Comment by SlicewOw** [comment]
Siehe: https://github.com/SlicewOw/webSPELL_Cups/issues/67
