### ISSUE TITLE
Cup action joincup Designfehler

### ISSUE THREAD

**Issue by xxxrenegade** [SlicewOw/webSPELL_Cups#66]
Unter index.php?site=cup&action=joincup&id=x bootstrap panel-footer die Buttens nicht richtig angezeigt.
![unbenannt-2](https://user-images.githubusercontent.com/2109906/51551771-75ea4000-1e6f-11e9-888d-a24b849af3de.jpg)

**Comment by SlicewOw** [comment]
Auf der Demo-Seite ist alles i.O. - ich benötige weitere Infos von dir!

![image](https://user-images.githubusercontent.com/18439656/51555791-c0bc8580-1e78-11e9-95d9-e71950c14a33.png)

**Comment by xxxrenegade** [comment]
Problem sollte folgendermaßen gefixt werden:
`<div class="panel-footer clearfix">
  <div class="pull-left">
  </div>
  <div class="pull-right">
  </div>
</div>`

Sprich dem Umschliesendem div gibst du die CSS Klasse clearfix ;-)

Das `<div class="clear"></div>` kann komplett rausgenommen werden.

**Comment by SlicewOw** [comment]
Siehe: https://github.com/SlicewOw/webSPELL_Cups/issues/67
