### ISSUE TITLE
E-Mail Adresse wird geblockt

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#69]
Kannst du mir auf deiner Testseite einen Account mit Admin erstellen?

(E-Mail: calzone1@gmx.net)

meine @live.de E-Mail funktioniert nicht.

**Comment by CallioO** [comment]
oder ändere den bestehenden Account ab auf calzone1@gmx.net ,
dann kann ich mir darauf evtl. das PW requesten.

**Comment by SlicewOw** [comment]
Dein Account auf der Demo-Seite ist bereits seit längerem aktiviert. Einfach einloggen.

**Comment by CallioO** [comment]
es geht sich um das PW, dass ich anfordern wollte / muss.
Sonst wäre ich ja längst eingeloggt :P

**Comment by CallioO** [comment]
![unbenaasdsadsadasnnt](https://user-images.githubusercontent.com/17162324/51666019-611bc280-1fbd-11e9-9ef5-c6f5784cea7d.jpg)

Aber es kommt keine E-Mail an - Wäre ja grundsätzlich auch ratsam es als issue zu betrachten...

**Comment by SlicewOw** [comment]
Es ist nicht ratsam, da es ein Server Problem ist und nicht zu diesem Add-On gehört. Funktional gesehen, ist alles korrekt. 

(Ich bekomme eine Benachrichtigung, dass die E-Mail nicht gesendet werden konnte)

**Comment by CallioO** [comment]
Na dann..
PW was du mir geschickt hast geht nicht...
