### ISSUE TITLE
Teams module: Copy Quickjoin and change password without function

### ISSUE THREAD

**Issue by xxxrenegade** [SlicewOw/webSPELL_Cups#74]
Unter index.php?site=teams&action=admin&id=x haben die Buttens Quickjoin kopieren und Passwort ändern keine Funktion.

**Comment by SlicewOw** [comment]
Mit Firefox (Win7) funktioniert es einwandfrei.
Getestet auf der Demo-Seite (aktueller Stand ist ausgechecked).

**Comment by xxxrenegade** [comment]
Getestet unter Firefox 64.0.2 (64-Bit) und Google Chrome 71.0.3578.98 (Offizieller Build) (64-Bit)

**Comment by xxxrenegade** [comment]
Ok kann geschlossen werden lag daran weil ich die JS Sachen ans Ende vom Body gepackt habe und nicht in den Head.
