### ISSUE TITLE
Gameaccount module: SteamID Finder has no function

### ISSUE THREAD

**Issue by xxxrenegade** [SlicewOw/webSPELL_Cups#76]
Der SteamID Finder unter index.php?site=gameaccount hat keine Funktzion.

**Comment by SlicewOw** [comment]
Wird an einer fehlenden Einstellung in der settings.php liegen - meine Vermutung.
Auf der Demo-Seite geht die Funktion ohne Probleme.

![grafik](https://user-images.githubusercontent.com/18439656/51689731-85949080-1ff7-11e9-9e63-dace694825d3.png)

**Comment by xxxrenegade** [comment]
Du meinst unter cup/settings.php?! Den steam_api_key, habe ich eben noch mal extra neu generieren lassen. Der steht richtig drin und im Backend läuft das ganze auch.

**Comment by xxxrenegade** [comment]
Ok kann geschlossen werden lag daran weil ich die JS Sachen ans Ende vom Body gepackt habe und nicht in den Head.
