### ISSUE TITLE
Cup module: Streams target="_blank" bug

### ISSUE THREAD

**Issue by xxxrenegade** [SlicewOw/webSPELL_Cups#77]
Wenn man unter index.php?site=cup&action=details&id=x auf einen Stream klickt dann öffnet sich ein neues Fenser mit folgedem url Strucktur: https://www.homepage.de/www.homepage.de/index.php?site=streams&action=show&livID=x

**Comment by SlicewOw** [comment]
Als Installations-Schritt ist angegeben, dass die HP URL mit "http" (oder https) zu setzen ist. Andernfalls kann es zu Probleme führen, wie hier der Fall. Bitte in den Einstellungen ändern, dann sollte es auch kein Problem sein.
