### ISSUE TITLE
Language Switch unter Edit Profile ohne Funktion

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#79]
Wenn man unter Edit Profile die Sprache Deutsch wählt, wird die Seite weiter in Englisch dargestellt.

**Comment by SlicewOw** [comment]
Du musst dich neu einloggen, dann sollte der Mechanismus greifen.

Der Language Switch ist allerdings webSPELL bezogen, dort habe ich nichts verändert.
