### ISSUE TITLE
Gameaccounts have to be activated manually

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#8]
Das halte ich für kontraproduktiv, da es bei einem Turnierabend kurz vorher nochmal hektisch werden kann und viele sich in letzter Minute einschreiben wollen. Ich würde des eingetragenen Gameaccount **SOFORT** aktivieren!

**Comment by SlicewOw** [comment]
Per Design gewollt - sehe ich als ein mögliches Feature, dass pro Spiel entschieden werden kann, ob es manuell aktiviert werden muss oder nicht.

Bei Spielen wie CSGO sind manuelle Aktivierungen sehr gut, um zu wissen wer auf der Plattform spielt und wer nicht.

**Comment by CallioO** [comment]
okay, das ist ein gutes Argument (y)

**Comment by SlicewOw** [comment]
![grafik](https://user-images.githubusercontent.com/18439656/50165937-3ff0f380-02e6-11e9-8e56-3e5e722f807c.png)
