### ISSUE TITLE
User / Teams

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#80]
Hau mal ein paar mehr User rein, mit denen man auch mal bissel was testen kann...

Test_User 01
Test_User 02
Test_User 03
usw..

PW: test

Das gleiche mit Teams

**Comment by SlicewOw** [comment]
Ich habe einen Slack Kanal erstellt, wo wir uns besser austauschen können zwecks solcher Wünsche für die Demo Seite. Link ist auch bei der README hinzugefügt.

https://webspellcup-addon.slack.com
