### ISSUE TITLE
AC / GAMES - Notice: Undefined index

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#81]
Im Admincenter unter Spiele wird folgendes angezeigt:

> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 238
> 
> Notice: Undefined index: cup_auto_active in /var/www/clients/client1/web1/web/webSPELL_Cups/admin/games.php on line 241

**Comment by SlicewOw** [comment]
Fehlende Einstellung auf der Demo-Seite. Kein Bug des Add-Ons!

(fixed)
