### ISSUE TITLE
Status "Check-in" of 1on1 cups is displayed wrongly

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#84]
Bei einem **1on1 Cup** ist der Check-In Btn unter dem Countdown auf der Home Seite für Spieler blockiert, die einem Team angehören und kein Admin Status haben.

> Status: Check-in allowed for team admins!

**Comment by SlicewOw** [comment]
Ein Bild wäre gut gewesen :D 

![grafik](https://user-images.githubusercontent.com/18439656/51895575-c3eccf80-23aa-11e9-9fe3-608320ecd906.png)
