### ISSUE TITLE
Penalties cannot be edited

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#9]
Hat man einen Strafpunkt vergeben, lässt sicher dieser zeitlich nicht begrenzen oder komplett löschen, wenn man sich evtl. vertan hat.

**Comment by SlicewOw** [comment]
Die Dauer der Strafpunkte gestaltet sich anhand der Kategorie, die ausgewählt wird beim Erstellen.

**Comment by CallioO** [comment]
Okay, dann bleibt das editieren / löschen.
