### ISSUE TITLE
Steam ID Finder

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#91]
Beim Steam ID Finder stört mich, dass er anscheinend nur die CS:GO ID raussucht und halt den Communitynamen. Was ist mit anderen Spielen wie z.B. Rocket League?

Dazu kommt, dass bei CS:GO der Steam Community Profil Link als ID gefordert wird. 
Das ist aber doch eigentlich Quatsch, weil meine CS:GO ID ist ja eine mit 0:1:xxxxxx ?

**Comment by SlicewOw** [comment]
Beide IDs sind gleich zu verwenden, der damals existierende CS:GO Bot hat in der finalen Version die 64er ID verwendet. Falsch ist das absolut nicht.

Es gibt eine Umrechung von der 1:0:xxxxxx ID auf die 64er, die ist allerdings Fehleranfällig und hängt vom System ab - das möchte ich nicht. Die 64er ist eindeutig und funktioniert wie gewünscht.

Was ich vielleicht ändern sollte ist, dass die 64er ID auch bei der Suche ausgeben wird bzw. anstelle der 1:0:xxxxxx.

Die Suche hat nichts mit einem Spiel zu tun, wird durch das Entfernen der 1:0:xxxxx ID ggf. auch ersichtlicher.

**Comment by CallioO** [comment]
Ja, das ist auch ein Problem für mich, da ich mich mehr auf Rocket League und Hearthstone konzentrieren werden, aber gut ^^

**Comment by SlicewOw** [comment]
Damit wollte ich nicht sagen, dass das so bleiben soll. Nur die Anforderungen waren damals komplett andere :smile:
