### ISSUE TITLE
Checkin Probleme

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#94]
Ich bin mit einem 3-Mann Team bei einem 2on2 Turnier angemeldet.
Nun wollte ich mich einchecken und bekomme folgende Meldung:

> Player count of your team is incorrect.

Wir hatten ja das Thema das man nicht mit 2 Teams am Turnier teilnehmen kann, was ich zwar immer noch für unnötig finde, aber okay. Man sollte aber ein Team erstellen können mit 10 Mitgliedern und mit diesem Team an 2on2, 3on3, 4on4, 5on5... Turnieren teilnehmen können?!

**Comment by SlicewOw** [comment]
https://github.com/SlicewOw/webSPELL_Cups/issues/88
