### ISSUE TITLE
Team hinzufügen über das AC

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#95]
https://cup-addon.slicewow.de/admin/admincenter.php?site=cup&mod=cup&action=teamadd&id=5

Wählt man im Admincenter ein Team aus und möchte es dem Turnier hinzufügen erscheint folgende Seite:

![unbenannt](https://user-images.githubusercontent.com/17162324/51979924-bdd01f00-248e-11e9-8f91-06a0983e59fa.JPG)

**Comment by SlicewOw** [comment]
Mit dem Link von oben (Seite hast du neu geladen?):

![grafik](https://user-images.githubusercontent.com/18439656/51980684-12749980-2491-11e9-9f16-da852c38cfa2.png)

**Comment by CallioO** [comment]
Wenn du jetzt ein Team wählst und dann auf Team hinzufügen klickst, dann kommt der Fehler.
