### ISSUE TITLE
Add image viewer to cup match

### ISSUE THREAD

**Issue by CallioO** [SlicewOw/webSPELL_Cups#96]
Ich fände es schöner, wenn man nicht für jedes Bild einen Tab geöffnet bekommt.
Was hälst du denn von so einer Anzeige?

https://beta.nestic.de/match/1438

Außerdem würde ich die Kategorie bei Screenshots entfernen.

**Comment by SlicewOw** [comment]
Ist möglich, die aktuelle Lösung ist schlichtweg einfacher und erfüllt/-e den Zweck.

**Comment by SlicewOw** [comment]
Benutzter Viewer:
* https://www.jqueryscript.net/gallery/Tiny-Responsive-Lightbox-Gallery-Plugin-For-jQuery-Viewbox.html
* https://github.com/pgooood/viewbox
