### ISSUE TITLE
adding a new game

### ISSUE THREAD

**Issue by rozemek** [SlicewOw/webSPELL_Cups#99]
Hello. How can i add a new game to the list?

**Comment by CallioO** [comment]
You can add a new game via admincenter:

.../admin/admincenter.php?site=games

**Comment by SlicewOw** [comment]
You are familiar with webSPELL as a content management system?

**Comment by rozemek** [comment]
I worked long on wordpress but webspell is something new. I can see that the file structure is easier for instance theme editing. Is it possible to add the news section into this ?

**Comment by SlicewOw** [comment]
This is just an add-on, so all basic functions/pages from webSPELL are available of course!
You have to edit the index and stylesheet in general, but then no problem should appear.

**Comment by rozemek** [comment]
So if i would like to use one of these themes : https://www.gamer-templates.com/cms-templates/webspell-nor-templates.html how do i implement them? Editing the html files ?

**Comment by rozemek** [comment]
Or is there one main file where i can set the design of the website?

**Comment by rozemek** [comment]
Yes i have done all that. What i mean is how to implement this addon into a theme i would install. Does it go automatically or do i have to add anything to the theme from the cup addon to make it visible in the theme

**Comment by SlicewOw** [comment]
You have to install webSPELL NOR first. Then you have to copy&paste every file from the template to your homepage (just overwrite everything).

The last step is to integrate my add-on. Just overwrite everything again except the index.php - you need to merge the existing index.php with my changes.

**Comment by SlicewOw** [comment]
You may join our Slack chat, then we can help you further :)
